version: '3.8'


services:
  fastapi_app:
    build: .
    user: "1000"
    ports:
      - "8000:8000"
    volumes:
      - ./db_data:/app/db_data:rw
#    environment:
#      - DATABASE_URL=sqlite+aiosqlite:///app/db_data/tasks.db
#    entrypoint: ["sh", "-c", "chmod 777 /app/tasks.db && uvicorn main_pet_project:app --host 0.0.0.0 --port 8000"]
#    volumes:
#      - ./files_input:/app/files_input:rw
#      - ./files_output:/app/files_output:rw